let industry = [
    "Property-Casualty Insurers",
    "Finance/Investors Services",
    "Other Specialty Stores",
    "Savings Institutions",
    "Major Banks",
    "Computer Software: Programming, Data Processing",
    "Computer Software: Prepackaged Software",
    "Diversified Commercial Services",
    "Telecommunications Equipment",
    "Homebuilding",
    "Major Chemicals",
    "Industrial Machinery/Components",
    "Major Pharmaceuticals",
    "Biotechnology: Laboratory Analytical Instruments",
    "Biotechnology: Biological Products (No Diagnostic Substances)",
    "Medical/Dental Instruments",
    "Oil & Gas Production",
    "Semiconductors",
    "Multi-Sector Companies",
    "Medical Specialities",
    "Other Pharmaceuticals",
    "Biotechnology: In Vitro & In Vivo Diagnostic Substances",
    "EDP Services",
    "Medical/Nursing Services",
    "Office Equipment/Supplies/Services",
    "Auto Parts:O.E.M.",
    "Water Supply",
    "Electrical Products",
    "Aerospace",
    "Business Services",
    "Air Freight/Delivery Services",
    "Radio And Television Broadcasting And Communications Equipment",
    "Advertising",
    "Farming/Seeds/Milling",
    "Industrial Specialties",
    "Services-Misc. Amusement & Recreation",
    "Coal Mining",
    "Computer Communications Equipment",
    "Real Estate Investment Trusts",
    "Catalog/Specialty Distribution",
    "Television Services",
    "Rental/Leasing Companies",
    "Finance: Consumer Services",
    "Life Insurance",
    "Ordnance And Accessories",
    "Railroads",
    "Metal Fabrications",
    "Forest Products",
    "Automotive Aftermarket",
    "Biotechnology: Commercial Physical & Biological Resarch",
    "Banks",
    "Professional Services",
    "Computer Manufacturing",
    "Home Furnishings",
    "Biotechnology: Electromedical & Electrotherapeutic Apparatus",
    "Agricultural Chemicals",
    "Trucking Freight/Courier Services",
    "Motor Vehicles",
    "Restaurants",
    "Department/Specialty Retail Stores",
    "Finance Companies",
    "Construction/Ag Equipment/Trucks",
    "Military/Government/Technical",
    "Computer peripheral equipment",
    "Food Distributors",
    "Electric Utilities: Central",
    "Transportation Services",
    "Miscellaneous",
    "Electronic Components",
    "Plastic Products",
    "Department/Specialty Retail Stores",
    "Oil Refining/Marketing",
    "Consumer Specialties",
    "Aluminum",
    "Recreational Products/Toys",
    "Natural Gas Distribution",
    "Integrated oil Companies",
    "Publishing",
    "Textiles",
    "Marine Transportation",
    "Shoe Manufacturing",
    "Specialty Chemicals",
    "Precious Metals",
    "Containers/Packaging",
    "Investment Bankers/Brokers/Service",
    "RETAIL: Building Materials",
    "Oilfield Services/Equipment",
    "Pollution Control Equipment",
    "Newspapers/Magazines",
    "Computer Electronics",
    "Oil & Gas Production",
    "Business Services",
    "Oil Refining/Marketing",
    "Computer Software: Programming, Data Processing",
    "Water Supply",
    "Business Services",
    "Department/Specialty Retail Stores",
    "Hotels/Resorts",
    "Oil & Gas Production",
    "Packaged Foods",
    "Business Services",
    "Biotechnology: Electromedical & Electrotherapeutic Apparatus",
    "Business Services",
    "Biotechnology: Laboratory Analytical Instruments",
    "Water Supply",
    "Military/Government/Technical",
    "Business Services",
    "Oilfield Services/Equipment",
    "Business Services",
    "Computer Communications Equipment",
    "Department/Specialty Retail Stores",
    "Business Services",
    "Finance: Consumer Services",
    "Miscellaneous manufacturing industries",
    "Biotechnology: Biological Products (No Diagnostic Substances)",
    "Biotechnology: Commercial Physical & Biological Resarch",
    "Industrial Machinery/Components",
    "Restaurants",
    "Building operators",
    "Hotels/Resorts",
    "Auto Manufacturing",
    "Electrical Products",
    "Property-Casualty Insurers",
    "Broadcasting",
    "Finance Companies",
    "Metal Fabrications",
    "Building Products",
    "Steel/Iron Ore",
    "Specialty Insurers",
    "Water Supply",
    "Finance: Consumer Services",
    "Specialty Foods",
    "EDP Services",
    "Business Services",
    "Commercial Banks",
    "Oil & Gas Production",
    "Environmental Services",
    "Shoe Manufacturing",
    "Catalog/Specialty Distribution",
    "Computer peripheral equipment",
    "Other Consumer Services",
    "Home Furnishings",
    "Miscellaneous manufacturing industries",
    "Biotechnology: Electromedical & Electrotherapeutic Apparatus",
    "Movies/Entertainment",
    "Power Generation",
    "Meat/Poultry/Fish",
    "Commercial Banks",
    "Beverages (Production/Distribution)",
    "Biotechnology: Laboratory Analytical Instruments",
    "Medical Electronics",
    "Computers Software: Prepackaged Software",
    "Automotive Aftermarket",
    "Books",
    "Specialty Chemicals",
    "Finance: Consumer Services",
    "Real Estate",
    "Water Supply",
    "Telecommunications Equipment",
    "Finance/Investors Services",
    "Oilfield Services/Equipment",
    "Specialty Insurers",
    "Accident &Health Insurance",
    "Property-Casualty Insurers",
    "Industrial Specialties",
    "Power Generation",
    "Meat/Poultry/Fish",
    "Miscellaneous manufacturing industries",
    "Air Freight/Delivery Services",
    "Finance Companies",
    "Investment Managers",
    "Retail: Computer Software & Peripheral Equipment",
    "Packaged Foods",
    "Oil & Gas Production",
    "Water Supply",
    "Environmental Services",
    "Military/Government/Technical",
    "Catalog/Specialty Distribution",
    "Computer Software: Programming, Data Processing",
    "Auto Parts:O.E.M.",
    "Building Products",
    "Restaurants",
    "Business Services",
    "Apparel",
    "Hotels/Resorts",
    "Textiles",
    "Professional Services",
    "Retail: Building Materials",
    "Consumer Electronics/Video Chains",
    "Mining & Quarrying of Nonmetallic Minerals (No Fuels)",
    "Real Estate Investment Trusts",
    "Newspapers/Magazines",
    "Office Equipment/Supplies/Services",
    "Clothing/Shoe/Accessory Stores"
]
export { industry };